// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PWEBTaipei
{
    public partial class TaipeiWeather
    {
        public string Location { get; set; }
        public DateTime StartTime { get; set; }
        public DateTime EndTime { get; set; }
        public byte RainChance { get; set; }
        public byte Temperature { get; set; }
        public byte RelativeHumidity { get; set; }
        public byte MinCi { get; set; }
        public byte MaxCi { get; set; }
        public byte WindSpeed { get; set; }
        public string WindDirection { get; set; }
        public byte MinAt { get; set; }
        public byte MaxAt { get; set; }
        public byte MinTemperature { get; set; }
        public byte MaxTemperature { get; set; }
        public byte Uvi { get; set; }
        public byte Td { get; set; }
        public string Weather { get; set; }
        public string WeatherDescription { get; set; }
    }
}